<?php
/**
 * Core plugin functionality.
 *
 * @package SecuritytxtManager
 */

namespace SecuritytxtManager\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

use const SecuritytxtManager\Constants\CAPABILITY;
use const SecuritytxtManager\Constants\QUERY_VAR;

/**
 * Default setup routine
 *
 * @return void
 */
function setup() {
	add_action( 'init', __NAMESPACE__ . '\\add_rewrite_rules' );
	add_action( 'template_redirect', __NAMESPACE__ . '\\display_security_txt' );
	add_action( 'admin_init', __NAMESPACE__ . '\\add_capability' );
	add_filter( 'query_vars', __NAMESPACE__ . '\\query_vars' );
	add_filter( 'security_txt_content', __NAMESPACE__ . '\\maybe_add_credits' );
}

/**
 * Add rewrite rules for security.txt endpoints.
 *
 * @return void
 */
function add_rewrite_rules() {
	add_rewrite_rule( '^security\.txt$', 'index.php?' . QUERY_VAR . '=1', 'top' );
	add_rewrite_rule( '^\.well-known/security\.txt$', 'index.php?' . QUERY_VAR . '=1', 'top' );
}

/**
 * Register query vars.
 *
 * @param array $vars Public query vars.
 *
 * @return array
 */
function query_vars( $vars ) {
	$vars[] = QUERY_VAR;

	return $vars;
}

/**
 * Handle security.txt requests
 *
 * @return void
 */
function display_security_txt() {
	if ( ! is_security_txt_request() ) {
		return;
	}

	$settings = \SecuritytxtManager\Utils\get_settings();
	if ( ! empty( $settings['content'] ) ) {
		status_header( 200 );
		nocache_headers();
		header( 'Content-Type: text/plain; charset=utf-8' );
		echo esc_html( apply_filters( 'security_txt_content', $settings['content'] ) );
		exit;
	}

	status_header( 404 );
	nocache_headers();
	exit;
}

/**
 * Determine if the current request is for security.txt.
 *
 * @return bool
 */
function is_security_txt_request() {
	if ( (bool) get_query_var( QUERY_VAR ) ) {
		return true;
	}

	if ( empty( $_SERVER['REQUEST_URI'] ) ) {
		return false;
	}

	$request_path     = wp_parse_url( wp_unslash( $_SERVER['REQUEST_URI'] ), PHP_URL_PATH );
	$allowed_requests = [ '/security.txt', '/.well-known/security.txt' ];

	return in_array( $request_path, $allowed_requests, true );
}

/**
 * Add credits info to security.txt output
 *
 * @param string $content Security.txt content
 *
 * @return mixed|string
 */
function maybe_add_credits( $content ) {
	$settings = \SecuritytxtManager\Utils\get_settings();
	if ( $settings['credits'] ) {
		$content .= PHP_EOL;
		$content .= esc_html__( '# Generated by Security.txt Manager: https://wordpress.org/plugins/security-txt-manager', 'security-txt-manager' );
	}

	return $content;
}

/**
 * Map the capability administrator role
 *
 * @return void
 */
function add_capability() {
	$role = get_role( 'administrator' );
	if ( $role && ! $role->has_cap( CAPABILITY ) ) {
		$role->add_cap( CAPABILITY );
	}
}

/**
 * Activation routine.
 *
 * @return void
 */
function activate() {
	add_capability();
	add_rewrite_rules();
	flush_rewrite_rules();
}

/**
 * Remove capability on deactivation
 *
 * @return void
 */
function deactivate() {
	$role = get_role( 'administrator' );
	if ( $role ) {
		$role->remove_cap( CAPABILITY );
	}

	flush_rewrite_rules();
}
